[project]
name = "get_media_duration"
version = "1.1"
authors = [
    { name = "Sebastian Reategui", email = "seb.reategui@gmail.com" },
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]